"""baseline

Revision ID: 19f005c70494
Revises: 
Create Date: 2023-09-19 15:21:26.143550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19f005c70494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('phone_number', sa.String(length=50),
                              nullable=False),
                    sa.Column('id_number', sa.String(length=50),
                              nullable=False),
                    sa.Column('location', sa.String(length=50),
                              nullable=False),
                    sa.Column('role', sa.Enum('EMPLOYER', 'JOBSEEKER', 'ADMIN',
                                              name='roleenum'),
                              nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('date_updated', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('created_by', sa.String(length=100),
                              server_default='Unknown', nullable=False),
                    sa.Column('updated_by', sa.String(length=100),
                              server_default='Unknown', nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()),
                              server_default='{}', nullable=True),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('id_number'),
                    sa.UniqueConstraint('phone_number')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
