"""add jobs

Revision ID: 23c5b7347c27
Revises: 3d43dba6c5c4
Create Date: 2023-09-21 02:03:46.386880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23c5b7347c27'
down_revision = '3d43dba6c5c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('location', sa.String(), nullable=False),
                    sa.Column('positions', sa.Integer(), nullable=False),
                    sa.Column('category',
                              sa.Enum('CONSTRUCTION', 'FARMING', 'WAREHOUSE',
                                      'PLUMBING', 'GENERAL',
                                      name='jobcategoryenum'), nullable=False),
                    sa.Column('employer_id', sa.UUID(), nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('date_updated', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('created_by', sa.String(length=100),
                              server_default='Unknown', nullable=False),
                    sa.Column('updated_by', sa.String(length=100),
                              server_default='Unknown', nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()),
                              server_default='{}', nullable=True),
                    sa.ForeignKeyConstraint(['employer_id'],
                                            ['user.user_id'], ),
                    sa.PrimaryKeyConstraint('job_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
