"""add sms

Revision ID: 3d43dba6c5c4
Revises: 19f005c70494
Create Date: 2023-09-20 15:52:53.810323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d43dba6c5c4'
down_revision = '19f005c70494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_inbox',
                    sa.Column('sms_id', sa.UUID(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('sender', sa.String(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('date_updated', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('created_by', sa.String(length=100),
                              server_default='Unknown', nullable=False),
                    sa.Column('updated_by', sa.String(length=100),
                              server_default='Unknown', nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()),
                              server_default='{}', nullable=True),
                    sa.PrimaryKeyConstraint('sms_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_inbox')
    # ### end Alembic commands ###
